Repository which-ecosystem/which, pull requests merged in 2020-06, with the labels that each got.

#11 Add functionality to Poll component
  .eslintrc.json
  src/PollCard/PollCard.tsx
  src/index.tsx
  src/types.d.ts
Labels: enhancement

#13 Improve Header styles
  .eslintrc.json
  package-lock.json
  package.json
  src/Header/Header.tsx
  src/Header/SearchBar.tsx
  src/index.tsx
Labels: enhancement

#41 Votes
  package-lock.json
  package.json
  src/components/Feed/Feed.tsx
  src/components/PollCard/PercentageBar.tsx
  src/components/PollCard/PollCard.tsx
  src/index.tsx
  src/pages/AuthPage/SignUpForm.tsx
  src/pages/FeedPage/FeedPage.tsx
  src/pages/ProfilePage/ProfileInfo.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/requests.ts
  src/types.d.ts
Labels: feature

#45 Display Date on PollCard
  src/components/PollCard/PollCard.tsx
Labels: frontend

#49 Feed improvements
  package-lock.json
  package.json
  src/components/PollCard/PollCard.tsx
  src/components/UserStrip/UserStrip.tsx
  src/pages/FeedPage/FeedPage.tsx
Labels: frontend

#50 SearchBar functionality
  src/components/Header/Header.tsx
  src/components/Header/SearchBar.tsx
  src/components/UserStrip/UserStrip.tsx
  src/pages/ProfilePage/ProfileInfo.tsx
Labels: feature, frontend

#54 Use hooks logic
  src/components/Feed/Feed.tsx
  src/components/Header/Header.tsx
  src/components/Header/SearchBar.tsx
  src/components/PollCard/PollCard.tsx
  src/components/UserStrip/UserStrip.tsx
  src/hooks/useAuth.tsx
  src/hooks/useNavigate.tsx
  src/index.tsx
  src/pages/AuthPage/AuthPage.tsx
  src/pages/AuthPage/SignInForm.tsx
  src/pages/AuthPage/SignUpForm.tsx
  src/pages/FeedPage/FeedPage.tsx
  src/pages/FeedPage/PollSubmission.tsx
  src/pages/FeedPage/PollSubmissionImage.tsx
  src/pages/Page.tsx
  src/pages/ProfilePage/MoreMenu.tsx
  src/pages/ProfilePage/ProfileInfo.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/types.d.ts
Labels: feature
